#ifndef NORLIT_UTIL_PREPROCESSING_H

#define NORLIT_PP_CONCAT_IMPL(a,b) a##b
#define NORLIT_PP_CONCAT(a,b) NORLIT_PP_CONCAT_IMPL(a,b)
#define NORLIT_PP_CONCAT3(a,b,c) NORLIT_PP_CONCAT(NORLIT_PP_CONCAT(a,b),c)

#endif