#ifndef NORLIT_PP_TOBOOL_H
#define NORLIT_PP_TOBOOL_H

#include "../Basic.h"

#define NORLIT_PP_TOBOOL(x) NORLIT_PP_CONCAT_2(NORLIT_PP_TOBOOL_, x)

#define NORLIT_PP_TOBOOL_0  0
#define NORLIT_PP_TOBOOL_1  1
#define NORLIT_PP_TOBOOL_2  1
#define NORLIT_PP_TOBOOL_3  1
#define NORLIT_PP_TOBOOL_4  1
#define NORLIT_PP_TOBOOL_5  1
#define NORLIT_PP_TOBOOL_6  1
#define NORLIT_PP_TOBOOL_7  1
#define NORLIT_PP_TOBOOL_8  1
#define NORLIT_PP_TOBOOL_9  1
#define NORLIT_PP_TOBOOL_10 1
#define NORLIT_PP_TOBOOL_11 1
#define NORLIT_PP_TOBOOL_12 1
#define NORLIT_PP_TOBOOL_13 1
#define NORLIT_PP_TOBOOL_14 1
#define NORLIT_PP_TOBOOL_15 1
#define NORLIT_PP_TOBOOL_16 1
#define NORLIT_PP_TOBOOL_17 1
#define NORLIT_PP_TOBOOL_18 1
#define NORLIT_PP_TOBOOL_19 1
#define NORLIT_PP_TOBOOL_20 1
#define NORLIT_PP_TOBOOL_21 1
#define NORLIT_PP_TOBOOL_22 1
#define NORLIT_PP_TOBOOL_23 1
#define NORLIT_PP_TOBOOL_24 1
#define NORLIT_PP_TOBOOL_25 1
#define NORLIT_PP_TOBOOL_26 1
#define NORLIT_PP_TOBOOL_27 1
#define NORLIT_PP_TOBOOL_28 1
#define NORLIT_PP_TOBOOL_29 1
#define NORLIT_PP_TOBOOL_30 1
#define NORLIT_PP_TOBOOL_31 1
#define NORLIT_PP_TOBOOL_32 1

#endif
